# Generated by Django 4.2.1 on 2023-05-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "event_app",
            "0002_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.PositiveIntegerField(default=32),
            preserve_default=False,
        ),
    ]
